### ISSUE TITLE
It doesn't work on linux nodes with Puppet version 2016.2.1 (4.5.3)

### ISSUE THREAD

**Issue by saimailbox86** [puppetlabs/puppetlabs-pe_bulk_agent_install#11]
The module is able to install the agent properly but it doesn't stop, it keeps on trying to install it again and again even though it is installed.

[Test.zip](https://github.com/puppetlabs/puppetlabs-pe_bulk_agent_install/files/1189017/Test.zip)

**Comment by natemccurdy** [comment]
Resolved in #16
