### ISSUE TITLE
Guide specifies wrong filename for node list in bulk windows installation

### ISSUE THREAD

**Issue by zaclaw** [puppetlabs/puppetlabs-pe_bulk_agent_install#15]
The guide specifies that nodes should be listed in "agents.txt". The script expects the file to be named "nodes.txt" unless specified otherwise.

**Comment by natemccurdy** [comment]
Fixed in https://github.com/puppetlabs/puppetlabs-pe_bulk_agent_install/commit/6890d14c69660784d4d893a518c5aebde8bea538
